/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visão;

/**
 *
 * @author juan.fiuza
 */
public class TelinhaMultipla extends javax.swing.JFrame {

    /**
     * Creates new form TelinhaMultipla
     */
    public TelinhaMultipla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadiadorqst1 = new javax.swing.JRadioButton();
        jRsondaqst1 = new javax.swing.JRadioButton();
        jRturboqst1 = new javax.swing.JRadioButton();
        jRbarraqst1 = new javax.swing.JRadioButton();
        jRsurgeqst1 = new javax.swing.JRadioButton();
        jBotaoda1 = new javax.swing.JButton();
        jLrespda1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRturboqst2 = new javax.swing.JRadioButton();
        jRadiadorqst2 = new javax.swing.JRadioButton();
        jRbarraqst2 = new javax.swing.JRadioButton();
        jRsurgeqst2 = new javax.swing.JRadioButton();
        jRsondaqst2 = new javax.swing.JRadioButton();
        jBotaoda2 = new javax.swing.JButton();
        jLrespda2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Peça responsável pelo aumento de potencia no motor por meio de pressurização do ar na camara de combustivel");

        buttonGroup1.add(jRadiadorqst1);
        jRadiadorqst1.setForeground(new java.awt.Color(255, 255, 255));
        jRadiadorqst1.setText("Radiador");
        jRadiadorqst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadiadorqst1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRsondaqst1);
        jRsondaqst1.setForeground(new java.awt.Color(255, 255, 255));
        jRsondaqst1.setText("Sonda Lambda");

        buttonGroup1.add(jRturboqst1);
        jRturboqst1.setForeground(new java.awt.Color(255, 255, 255));
        jRturboqst1.setText("Turbo");

        buttonGroup1.add(jRbarraqst1);
        jRbarraqst1.setForeground(new java.awt.Color(255, 255, 255));
        jRbarraqst1.setText("Barra Antitorção");

        buttonGroup1.add(jRsurgeqst1);
        jRsurgeqst1.setForeground(new java.awt.Color(255, 255, 255));
        jRsurgeqst1.setText("Surge Tank ");

        jBotaoda1.setText("Escolha");
        jBotaoda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoda1ActionPerformed(evt);
            }
        });

        jLrespda1.setText("Resposta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jRadiadorqst1)
                        .addGap(37, 37, 37)
                        .addComponent(jRsondaqst1)
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRturboqst1)
                            .addComponent(jBotaoda1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRbarraqst1)
                                .addGap(38, 38, 38)
                                .addComponent(jRsurgeqst1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLrespda1)))))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadiadorqst1)
                    .addComponent(jRsondaqst1)
                    .addComponent(jRbarraqst1)
                    .addComponent(jRsurgeqst1)
                    .addComponent(jRturboqst1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotaoda1)
                    .addComponent(jLrespda1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dispositivo que auxilia o carro em altas velocidades onde a gravidade atrapalha a injeção de combustivel ativando o mesmo");

        buttonGroup2.add(jRturboqst2);
        jRturboqst2.setForeground(new java.awt.Color(255, 255, 255));
        jRturboqst2.setText("Turbo");

        buttonGroup2.add(jRadiadorqst2);
        jRadiadorqst2.setForeground(new java.awt.Color(255, 255, 255));
        jRadiadorqst2.setText("Radiador");
        jRadiadorqst2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadiadorqst2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRbarraqst2);
        jRbarraqst2.setForeground(new java.awt.Color(255, 255, 255));
        jRbarraqst2.setText("Barra Antitorção");

        buttonGroup2.add(jRsurgeqst2);
        jRsurgeqst2.setForeground(new java.awt.Color(255, 255, 255));
        jRsurgeqst2.setText("Surge Tank ");

        buttonGroup2.add(jRsondaqst2);
        jRsondaqst2.setForeground(new java.awt.Color(255, 255, 255));
        jRsondaqst2.setText("Sonda Lambda");

        jBotaoda2.setText("Escolha");
        jBotaoda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoda2ActionPerformed(evt);
            }
        });

        jLrespda2.setText("Resposta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jRadiadorqst2)
                .addGap(47, 47, 47)
                .addComponent(jRsondaqst2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRturboqst2)
                .addGap(53, 53, 53)
                .addComponent(jRbarraqst2)
                .addGap(39, 39, 39)
                .addComponent(jRsurgeqst2)
                .addGap(29, 29, 29))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jBotaoda2)
                        .addGap(67, 67, 67)
                        .addComponent(jLrespda2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadiadorqst2)
                    .addComponent(jRsondaqst2)
                    .addComponent(jRturboqst2)
                    .addComponent(jRbarraqst2)
                    .addComponent(jRsurgeqst2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotaoda2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLrespda2))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel3.setText("Aulinha de Preparação Automotiva ");

        jLabel4.setText("Total de acertos : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadiadorqst2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadiadorqst2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadiadorqst2ActionPerformed

    private void jRadiadorqst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadiadorqst1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadiadorqst1ActionPerformed

    private void jBotaoda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotaoda2ActionPerformed

    private void jBotaoda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoda1ActionPerformed
        // TODO add your handling code here:
        if (jRadiadorqst1.isSelected()) {
            
            
        }
    }//GEN-LAST:event_jBotaoda1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelinhaMultipla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelinhaMultipla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelinhaMultipla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelinhaMultipla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelinhaMultipla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBotaoda1;
    private javax.swing.JButton jBotaoda2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLrespda1;
    private javax.swing.JLabel jLrespda2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadiadorqst1;
    private javax.swing.JRadioButton jRadiadorqst2;
    private javax.swing.JRadioButton jRbarraqst1;
    private javax.swing.JRadioButton jRbarraqst2;
    private javax.swing.JRadioButton jRsondaqst1;
    private javax.swing.JRadioButton jRsondaqst2;
    private javax.swing.JRadioButton jRsurgeqst1;
    private javax.swing.JRadioButton jRsurgeqst2;
    private javax.swing.JRadioButton jRturboqst1;
    private javax.swing.JRadioButton jRturboqst2;
    // End of variables declaration//GEN-END:variables
}
