/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao;

import br.com.controle.Divisao;
import br.com.controle.Media;
import br.com.controle.Multiplicacao;
import br.com.controle.OperacaoMatematics;
import br.com.controle.Soma;
import br.com.controle.Subtracao;
import javax.swing.JOptionPane;

/**
 *
 * @author juan.fiuza
 */
public class TelaDaTelaSobreTela extends javax.swing.JFrame {

    public static double calcule(OperacaoMatematics op, double valor1, double valor2){
    return op.calcular(valor1, valor2);
    }
    /**
     * Creates new form TelaDaTelaSobreTela
     */
    public TelaDaTelaSobreTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTvalor1 = new javax.swing.JTextField();
        jTvalor2 = new javax.swing.JTextField();
        jBsomar = new javax.swing.JButton();
        jLresultado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBsubtracao = new javax.swing.JButton();
        jBmult = new javax.swing.JButton();
        jdivi = new javax.swing.JButton();
        jBmedia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Valor 1:");

        jLabel2.setText("Valor 2:");

        jBsomar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBsomar.setText("+");
        jBsomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsomarActionPerformed(evt);
            }
        });

        jLresultado.setText("0.00");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Calculator 3.000");

        jBsubtracao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBsubtracao.setText("-");
        jBsubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsubtracaoActionPerformed(evt);
            }
        });

        jBmult.setText("x");
        jBmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmultActionPerformed(evt);
            }
        });

        jdivi.setText("/");
        jdivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdiviActionPerformed(evt);
            }
        });

        jBmedia.setText("Media");
        jBmedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmediaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTvalor1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(jTvalor2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBsomar)
                                .addGap(18, 18, 18)
                                .addComponent(jBsubtracao)
                                .addGap(18, 18, 18)
                                .addComponent(jBmult)
                                .addGap(18, 18, 18)
                                .addComponent(jdivi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBmedia))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLresultado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel3)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsomar)
                    .addComponent(jBsubtracao)
                    .addComponent(jBmult)
                    .addComponent(jdivi)
                    .addComponent(jBmedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLresultado)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsomarActionPerformed
        // TODO add your handling code here:
         if(jTvalor1.getText().equals("")){
            JOptionPane.showMessageDialog(null," Campo Obrigatório!");
            jTvalor1.requestFocus();
        }
        else if (jTvalor2.getText().equals("")){
            JOptionPane.showMessageDialog(null," Campo Obrigatório!");
            jTvalor2.requestFocus();
        }else{
        double pvalor1=Double.valueOf(jTvalor1.getText());
        double pvalor2 =Double.valueOf(jTvalor2.getText());
        jLresultado.setText("Soma: "+calcule(new Soma(), pvalor1,pvalor2));
        jTvalor1.setText("");
        jTvalor2.setText("");
        jTvalor1.requestFocus();
        
        
        }
    }//GEN-LAST:event_jBsomarActionPerformed

    private void jBsubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsubtracaoActionPerformed
        // TODO add your handling code here:
         if(jTvalor1.getText().equals("")){
            JOptionPane.showMessageDialog(null," Campo Obrigatório!");
            jTvalor1.requestFocus();
        }
        else if (jTvalor2.getText().equals("")){
            JOptionPane.showMessageDialog(null," Campo Obrigatório!");
            jTvalor2.requestFocus();
        }else{
        double pvalor1=Double.valueOf(jTvalor1.getText());
        double pvalor2 =Double.valueOf(jTvalor2.getText());
        jLresultado.setText("Subtração: "+calcule(new Subtracao(), pvalor1,pvalor2));
        jTvalor1.setText("");
        jTvalor2.setText("");
        jTvalor1.requestFocus();
        
        
        }
    
        
    }//GEN-LAST:event_jBsubtracaoActionPerformed

    private void jBmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmultActionPerformed
        // TODO add your handling code here:
         if(jTvalor1.getText().equals("")){
            JOptionPane.showMessageDialog(null," Campo Obrigatório!");
            jTvalor1.requestFocus();
        }
        else if (jTvalor2.getText().equals("")){
            JOptionPane.showMessageDialog(null," Campo Obrigatório!");
            jTvalor2.requestFocus();
        }else{
        double pvalor1=Double.valueOf(jTvalor1.getText());
        double pvalor2 =Double.valueOf(jTvalor2.getText());
        jLresultado.setText("Multiplicação: "+calcule(new Multiplicacao(), pvalor1,pvalor2));
        jTvalor1.setText("");
        jTvalor2.setText("");
        jTvalor1.requestFocus();
        
        
        }
      
    }//GEN-LAST:event_jBmultActionPerformed

    private void jdiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdiviActionPerformed
        // TODO add your handling code here:
         if(jTvalor1.getText().equals("")){
            JOptionPane.showMessageDialog(null," Campo Obrigatório!");
            jTvalor1.requestFocus();
        }
        else if (jTvalor2.getText().equals("")){
            JOptionPane.showMessageDialog(null," Campo Obrigatório!");
            jTvalor2.requestFocus();
        }else{
        double pvalor1=Double.valueOf(jTvalor1.getText());
        double pvalor2 =Double.valueOf(jTvalor2.getText());
        jLresultado.setText("Divisão: "+calcule(new Divisao(), pvalor1,pvalor2));
        jTvalor1.setText("");
        jTvalor2.setText("");
        jTvalor1.requestFocus();
        
        
        }
     
    }//GEN-LAST:event_jdiviActionPerformed

    private void jBmediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmediaActionPerformed
        // TODO add your handling code here:
         if(jTvalor1.getText().equals("")){
            JOptionPane.showMessageDialog(null," Campo Obrigatório!");
            jTvalor1.requestFocus();
        }
        else if (jTvalor2.getText().equals("")){
            JOptionPane.showMessageDialog(null," Campo Obrigatório!");
            jTvalor2.requestFocus();
        }else{
        double pvalor1=Double.valueOf(jTvalor1.getText());
        double pvalor2 =Double.valueOf(jTvalor2.getText());
        jLresultado.setText("Media: "+calcule(new Media(), pvalor1,pvalor2));
        jTvalor1.setText("");
        jTvalor2.setText("");
        jTvalor1.requestFocus();
        
        }
    
    }//GEN-LAST:event_jBmediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDaTelaSobreTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDaTelaSobreTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDaTelaSobreTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDaTelaSobreTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDaTelaSobreTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBmedia;
    private javax.swing.JButton jBmult;
    private javax.swing.JButton jBsomar;
    private javax.swing.JButton jBsubtracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLresultado;
    private javax.swing.JTextField jTvalor1;
    private javax.swing.JTextField jTvalor2;
    private javax.swing.JButton jdivi;
    // End of variables declaration//GEN-END:variables
}
